### ISSUE TITLE
Move code out of GL_DetailPosting_upd

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#105]
There is code in here that writes sync records. Please move this to the GL558_YIBDetailPosting_upd class override. For some reason it's not there, I'm not sure why.

**Comment by SmartBusinessProcess** [comment]
Hello @chiefchef ,

I have completed this task.
The install package is attached. Please download and install it. This package contains the original GL_DetailPosting_upd.pvc for overwriting the modified file.
[MoveCodeOutGL_DetailPosting_upd.zip](https://github.com/yibastechnology/GTS2017_PU2/files/6056517/MoveCodeOutGL_DetailPosting_upd.zip)
