### ISSUE TITLE
Add note to Sales Order Acknowledgement

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#45]
- [x] If the item doesn't have AllowReturns$ = "Y" then the line needs to say:
*This item is non-returnable. Please see below for more information.
- [x] If any 1 product has this we need to add this message to the footer of the report:
NOTE: This order contains one or more special inventory item(s) and is subject to the following return policy. Items purchased as special inventory/special quote are non-refundable and non-returnable. In the event a return is approved by Global, the customer will be responsible for any and all freight charges as well as any applicable restocking fee.  Please ensure accuracy of your order prior to submission for processing.  

[SO_SalesOrder2.zip](https://github.com/yibastechnology/GTS2017_PU2/files/4371303/SO_SalesOrder2.zip)

**Comment by SmartBusinessProcess** [comment]
Completed
