### ISSUE TITLE
AP Aging

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#49]
- [ ] Need to add 5 aging field to AP_Vendor the same way they exist in AR_Customer
- [ ] Need to write routines that update the 4 new Vendor aging fields similar to how AR_Customer aging works.

**Comment by steezware** [comment]
Created spec
[GTS-Spec-49-ApAging.docx](https://github.com/yibastechnology/GTS2017_PU2/files/5811417/GTS-Spec-49-ApAging.docx)

**Comment by steezware** [comment]
Dropbox link to spec: https://www.dropbox.com/scl/fi/s0ruygzamz7z9a2osszep/GTS-Spec-49-ApAging.docx?dl=0&rlkey=x0qaqpm9ibpif2a37df84zd12

**Comment by steezware** [comment]
Question: Are these the aging amts that you want added to AP Vendor?
![Issue49-01](https://user-images.githubusercontent.com/32148091/104525231-f0607d00-55bc-11eb-8d91-8739594f7011.png)

**Comment by chiefchef** [comment]
Yes

**Comment by chiefchef** [comment]
I say add the fields and do it the same way AR does it.

**Comment by chiefchef** [comment]
@steezware Take a look at the following class in the YIB repo CI558_YIBCustomerAging:
https://github.com/yibastechnology/YIB2017_PU2/blob/master/YIB2017_PU2_Source/CI/CI558_YIBCustomerAging.pvc

You will see how I'm writing the sync records for the customer aging. I'm assuming you would need to create a CI558_GTSVendorAging class and add a method similar to UpdateAging() that is found in CI_CustomerAging. Also, we'd need to add the hooks for syncing to our database. Hopefully this is enough to get you going.
