### ISSUE TITLE
Schedule and Email B/M Production History Report

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#51]
- [x] From Email - noreply@globalthesource.com
- [x] To Email - jonathank@globalthesource.com
- [x] Make the date DTE(0)
- [x] Schedule for 6 PM

![image](https://user-images.githubusercontent.com/15325459/104494330-f003ba00-559b-11eb-8bcf-3e106687473f.png)

**Production Header Section of Report**
- [x] Remove decimals from the Quantity on the header of the report. For this example it should just read 245. Our finished goods are always integers.
- [x] Remove Lot/Serial Header
- [x] Remove Unit of Measure Column (Right now we are only using Each)

**Production Detail Section of Report**
- [x] Remove Revision Column
- [x] Remove Unit of Measure Column (Right now we are only using Each)
- [x] Remove Whse Column (Right now we are only using 000 for Components)
- [x] Add "Last Cost" column that pulls the last ROG cost
- [x] Add "Extended Last Cost" column that extends new "Last Cost" and "Extended Quantity"
- [x] Add "Last Receipt Date" that pulls the last date received

**Comment by SmartBusinessProcess** [comment]
I have completed this and created a pull request.
