### ISSUE TITLE
Sync - Background Monitor

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#62]

**Comment by steezware** [comment]
Notes from mtg with Jonathan Feb 3...

[X ] 1. Create utility to scan properties in YIBSync_bus to fetch MAIN table names
[  ] 2. Make sure bkgd process can run on the live system without any impact
[  ] 3. Dupe the YIB_Class - be LIKE it - and only change the MAIN table to SY558_YIBSyncMongo
[  ] 4. In ProcessTables make sure my new YIB sync class is instantiated and use it to write to the new MAIN table CREATE/UPDATE/DELETE
[  ] 5. Figure out a way to prioritize the tables being scanned - some are more active and important than others.

**Comment by steezware** [comment]
[ ] 6. Remove the "sleep minutes" setting, necessary because we need to prioritize tables to scan and having one value for sleeping between scans is not sensible.

**Comment by chiefchef** [comment]
Possible strategies to optimize AR_InvoiceHistoryHeader/Detail
- Add Date to AR_InvoiceHistoryDetail table - and add new alternate key
- Use Invoice Numbers from SO_InvoiceHeader/Detail
