### ISSUE TITLE
Allow Standard Cost Adjustment while Syncing

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#70]
We need to allow Standard Cost Adjustment while the C# sync tool is running. Ultimately we will need to find out what exactly the Standard Cost Adjustment Utility actually does and why Sage requires exclusive access to files.

**Comment by steezware** [comment]
Is this referring to the IM tasks on the Utilities Menu, namely these?
Standard Cost Adjustment Selection
Standard Cost Adjustment Entry
Standard Cost Adjustment Register/Update

**Comment by steezware** [comment]
And what exactly is happening with the C# sync tool? Is it failing in an attempt to access a business object, or something else? If a business object failure, what is the error - what is happening in the C# code that fails?

**Comment by chiefchef** [comment]
I'm just going to can this project. I'll continue restarting the sync tool.
