### ISSUE TITLE
Write Sync Record IM_ItemWarehouse

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#71]
All times that IM_ItemWarehouse with Multi-Bin Disabled has a WRITE/REMOVE a sync record needs to be written to the system. Please update the following files by using this code to write out a sync record:

			IF coSY558_YIBSync_bus'GetNextSyncNo(tmpSyncNo$, "B") {
				coSY558_YIBSync_bus'SetKeyValue("Priority$", "B")
				coSY558_YIBSync_bus'SetKeyValue("SyncNo$", tmpSyncNo$)

				IF coSY558_YIBSync_bus'SetKey() {
					tmpRetVal = coSY558_YIBSync_bus'SetValue("Action$", "UPDATE")
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageClass$", _OBJ'_Class$)
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageCompanyCode$", coSession'CompanyCode$)
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageKeyDefinition$", "KPRIMARY")
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageKeyValue$", tmpKey$)
					tmpRetVal = coSY558_YIBSync_bus'SetValue("MongoCollectionName$", "PRODUCTWAREHOUSEBINS")
					tmpRetVal = coSY558_YIBSync_bus'Write()
				}
			}

The files can be found in this spreadsheet:
https://globalthesource1.sharepoint.com/:x:/s/Test/EY7dI5iCcTtDu5Wl0ihHt3UBXedHbbjxhlTw8tNZQg9sRQ?e=OuvvbQ

For a REMOVE this is the code:

			IF coSY558_YIBSync_bus'GetNextSyncNo(tmpSyncNo$, "B") {
				coSY558_YIBSync_bus'SetKeyValue("Priority$", "B")
				coSY558_YIBSync_bus'SetKeyValue("SyncNo$", tmpSyncNo$)

				IF coSY558_YIBSync_bus'SetKey() {
					tmpRetVal = coSY558_YIBSync_bus'SetValue("Action$", "DELETE")
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageClass$", _OBJ'_Class$)
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageCompanyCode$", coSession'CompanyCode$)
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageKeyDefinition$", "KPRIMARY")
					tmpRetVal = coSY558_YIBSync_bus'SetValue("SageKeyValue$", tmpKey$)
					tmpRetVal = coSY558_YIBSync_bus'SetValue("MongoCollectionName$", "PRODUCTWAREHOUSEBINS")
					tmpRetVal = coSY558_YIBSync_bus'Write()
				}
			}

**Comment by SmartBusinessProcess** [comment]
[AliasItemModPackage.zip](https://github.com/yibastechnology/GTS2017_PU2/files/5905651/AliasItemModPackage.zip)

**Comment by SmartBusinessProcess** [comment]
Hello,

I have completed this task.
The install package is attached.
[WriteSyncRecordIM_ItemWarehousePackage.zip](https://github.com/yibastechnology/GTS2017_PU2/files/5906531/WriteSyncRecordIM_ItemWarehousePackage.zip)

**Comment by SmartBusinessProcess** [comment]
Hello @chiefchef ,

Here is the updated package.
I have added the Multi-Bin Disabled checking.
[WriteSyncRecordIM_ItemWarehousePackage.zip](https://github.com/yibastechnology/GTS2017_PU2/files/5913781/WriteSyncRecordIM_ItemWarehousePackage.zip)
