### ISSUE TITLE
Restore $0 AP Open Invoices

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#81]
- [ ] Reststore AP_OpenInvoice from backup

**Comment by chiefchef** [comment]
These are the files. I have put the dates on the file name:
[AP_OpenInvoice.zip](https://github.com/yibastechnology/GTS2017_PU2/files/5935743/AP_OpenInvoice.zip)

**Comment by SmartBusinessProcess** [comment]
Hello @chiefchef 

The updated AP_OpenInvoice.M4T table is attached.
[AP_OpenInvoice.zip](https://github.com/yibastechnology/GTS2017_PU2/files/5939220/AP_OpenInvoice.zip)
