### ISSUE TITLE
Force Item Warehouse Bin Record

### ISSUE THREAD

**Issue by chiefchef** [yibastechnology/GTS2017_PU2#83]
On this method I need for the system to just create the record if it doesn't exist:

retVal = Convert.ToInt16(oBinDistribution.InvokeMethod("nAddDistributionLine", "X"));

Use similar logic as this:

AUTO_PRIMARY_BIN_DISTRIBUTION:

!	coIM_ItemWarehouse_svc
	
		
!	coIM_ItemWarehouse_svc'SetKeyValue("ItemCode$", ItemCode$)
!	coIM_ItemWarehouse_svc'SetKeyValue("WarehouseCode$", WarehouseCode$)
!			
!	IF coIM_ItemWarehouse_svc'Find() {
!		coIM_ItemWarehouse_svc'GetPrimaryBin$("QuantityOnHand", BM558_GTSAutoGenOrdersApv.FinishedQuantity)
!	}	
	
	READ DATA FROM $$,REC=itemwhse$ TO IOL=IOL(cWARItemWarehouseFH)
	READ(cWARItemWarehouseFH,KEY=ItemCode$:WarehouseCode$,REC=itemwhse$,DOM=*NEXT)

	IF NOT(NUL(itemwhse.D558_WARPrimaryBinLocation$)) {
		IF NOT(coWARItemWhseBinSvc'IsValidBinLocation(ItemCode$,WarehouseCode$,$$,itemwhse.D558_WARPrimaryBinLocation$)) AND cAllowUseWhseBins AND CommitBinQty {
			_OBJ'WriteNewItemWhseBin((ItemCode$),(WarehouseCode$),($$),(itemwhse.D558_WARPrimaryBinLocation$),($$))
		}
		
		_OBJ'RemoveBinLines(DocumentNo$,Linekey$)
		retVal = _OBJ'AddDistributionLine(itemwhse.D558_WARPrimaryBinLocation$)
		IF retVal = edtNEW {
			retVal = _OBJ'Write()
		}
	}

	RETURN retVal

**Comment by SmartBusinessProcess** [comment]
Hello @chiefchef 

I have updated the CI558_WARCommonBinDistribution.pvc program in the WAR2017_PU2 repository.
I have added the "CreateItemWhseBin" property in the bin distribution object and it is necessary to set the 1 in the "CreateItemWhseBin" property before calling the AddDistributionLine line method.
